### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by infinigrove** [Roastero/freshroastsr700#16]
In the Setting up a development environment section @ http://freshroastsr700.readthedocs.io/en/latest/contributing.html

The line:

    git clone git@github.com:Roastero/freshroastsr700.git

Should be:

    git clone https://github.com/Roastero/freshroastsr700.git

**Comment by CCoffie** [comment]
Either of the commands will work. The first command is what you would use if you have ssh keys setup with github.

**Comment by infinigrove** [comment]
Ok, I don't have ssh keys setup with github.  That would probably explain why it wouldn't work for me.

Thanks for explaining.
