### ISSUE TITLE
freshroastsr700 hangs on exit

### ISSUE THREAD

**Issue by int3ll3ct** [Roastero/freshroastsr700#17]
The existing test suite does not include hardware in the loop.  The way the multiprocessing support is implemented, there are problems on exit when threads were previously spun up, either for comms or for the PID controller.  

To reproduce, make thermostat=True in the object instantiation in the test suite. nosetests hang due to the thermostat thread somehow not exiting (I haven't root caused it). Putting .daemon=True before all calls to .start() resolves this issue, in my testing.   Setting .daemon=True forces the threads to close when the main freshroastsr700 process exits.  After this, even with object instantiations with thermostat=True, everything exits properly.

Here's an example of the required mod. 
```
        if(thermostat is True):
            self.thermostat_process = mp.Process(target=self.thermostat)
            self.thermostat_process.daemon = True
            self.thermostat_process.start()
```

I don't want to screw up the OpenRoast app, so rather than submit a pull request, I thought I'd just note this here for now.  In my development, I'll be using this code and once I'm satisfied that it truly behaves as intended, I can submit a pull request.

**Comment by betterengineering** [comment]
Hey, thanks for putting this together @int3ll3ct! If you do find it behaves as expected, please submit a pull request with the required changes.

**Comment by int3ll3ct** [comment]
Pull request submitted and accepted that addresses this issue, as of v0.2.0dev8.
