### ISSUE TITLE
Switch to multiprocessing

### ISSUE THREAD

**Issue by betterengineering** [Roastero/freshroastsr700#8]
The current use of threads cause massive slow downs when building applications off of this module due to the [GIL](https://docs.python.org/2/glossary.html#term-global-interpreter-lock). The threads should be replaced with processes using [multiprocessing](https://docs.python.org/2/library/multiprocessing.html) to side-step the GIL.

**Comment by dankolbman** [comment]
Why don't you just [remove the GIL](https://youtu.be/BWyDA5y6TIg?t=11m38s)????

**Comment by kmorey** [comment]
How do you know the GIL is the problem? I've rarely needed threads to update so fast the GIL was the actual bottleneck, but I have encountered it.

Poking around a bit with a borrowed roaster, it seems the timer function could be problematic. The loop only sleeps if the state is roasting or cooling. Outside those two states the loop is going to be thrashing the CPU with no sleep at all.

**Comment by betterengineering** [comment]
Commit ca05c89cf370aef514f14f1ee902a0cfc207c951 by @kmorey has solved this issue.
